use_cuda: false

model_name: skipgram

dataset: None
data_dir: data/
train_batch_size: 16
val_batch_size: 16
shuffle: True

optimizer: Adam
learning_rate: 0.025
epochs: 16
train_steps: -1
val_steps: -1

checkpoint_frequency: 4
model_dir: models/skipgram_test
